spring.application.name: employee-api
server.port: 8111

logging:
  level:
    org.springframework.web.client: ERROR

app:
  logger:
    log-level: INFO
  rest:
      maxattempts: 20
      timeout:
        connect: 10
        read: 120
      backoff:
        fixedinterval: 5000

