spring.application.name: employee-api
server.port: 8111

app:
  logger:
    log-level: DEBUG
  rest:
      maxattempts: 20
      timeout:
        connect: 10
        read: 120
      backoff:
        fixedinterval: 5000

